baseURL = "https://austinpocus.com/"
languageCode = "en-us"
title = "ajpocus's notes"
theme = "ananke"

[deployment]

[[deployment.targets]]

name = "production"
URL = "s3://austinpocus.com?region=us-east-1"
cloudfront = "ELJZDBLCTCBH2"