baseURL = "https://blog.austinpocus.com/"
languageCode = "en-us"
title = "notes by ajpocus"
description = "The personal blog of Austin Pocus"
theme = "simpleness"
googleAnalytics = "UA-185432483-1"
summaryLength = "160"

[related]
includeNewer = false
threshold = 80
toLower = false
[[related.indices]]
name = 'tags'
weight = 100
[[related.indices]]
name = 'date'
weight = 10

[params]
  description = "The personal blog of Austin Pocus"
  title = "notes by ajpocus"

[taxonomies]
  tags = "tags"

[menu]

  [[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = -105

  [[menu.main]]
    name = "about"
    url = "https://austinpocus.com"
    weight = -100

[deployment]

[[deployment.targets]]

name = "production"
URL = "s3://austinpocus.com?region=us-east-1"
cloudfront = "ELJZDBLCTCBH2"

