baseURL = "https://blog.austinpocus.com/"
languageCode = "en-us"
title = "notes by Austin Pocus"
description = "The personal blog of Austin Pocus"
theme = "simpleness"
summaryLength = "160"

[related]
includeNewer = false
threshold = 80
toLower = false
[[related.indices]]
name = 'tags'
weight = 100
[[related.indices]]
name = 'date'
weight = 10

[params]
  description = "The personal blog of Austin Pocus"
  title = "notes by Austin Pocus"

[taxonomies]
  tags = "tags"

[menu]

  [[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = -110

  [[menu.main]]
    name = "about"
    url = "https://austinpocus.com"
    weight = -105
  
  # [[menu.main]]
  #   name = "subscribe"
  #   url = "https://subscribe.austinpocus.com/get-new-posts"
  #   weight = -100
