baseURL = "https://austinpocus.com/"
languageCode = "en-us"
title = "notes by ajpocus"
description = "The personal blog of Austin Pocus"
theme = "simpleness"
googleAnalytics = "UA-185432483-1"
summaryLength = "160"

[params]
  description = "The personal blog of Austin Pocus"
  images = ["img/me.jpg"]
  title = "notes by ajpocus"

[taxonomies]
  tags = "tags"

[menu]

  [[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = -105

  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = -100

[deployment]

[[deployment.targets]]

name = "production"
URL = "s3://austinpocus.com?region=us-east-1"
cloudfront = "ELJZDBLCTCBH2"

